package CheckJob;

use Modern::Perl;
use XML::Rabbit::Root;

has_xpath_value aw_duration       => '//Data/job/@AWDuration';
has_xpath_value account           => '//Data/job/@Account';
has_xpath_value block_reason      => '//Data/job/@BlockReason';
has_xpath_value class             => '//Data/job/@Class';
has_xpath_value drm_jid           => '//Data/job/@DRMJID';
has_xpath_value ee_duration       => '//Data/job/@EEDuration';
has_xpath_value efile             => '//Data/job/@EFile';
has_xpath_value estate            => '//Data/job/@EState';
has_xpath_value effpal            => '//Data/job/@EffPAL';
has_xpath_value flags             => '//Data/job/@Flags';
has_xpath_value gattr             => '//Data/job/@GAttr';
has_xpath_value group             => '//Data/job/@Group';
has_xpath_value job_id            => '//Data/job/@JobID';
has_xpath_value job_name          => '//Data/job/@JobName';
has_xpath_value mail_user         => '//Data/job/@MailUser';
has_xpath_value notification      => '//Data/job/@Notification';
has_xpath_value ofile             => '//Data/job/@OFile';
has_xpath_value pal               => '//Data/job/@PAL';
has_xpath_value qos               => '//Data/job/@QOS';
has_xpath_value qos_req           => '//Data/job/@QOSReq';
has_xpath_value queue_status      => '//Data/job/@QueueStatus';
has_xpath_value rm                => '//Data/job/@RM';
has_xpath_value rm_stderr         => '//Data/job/@RMStdErr';
has_xpath_value rm_stdout         => '//Data/job/@RMStdOut';
has_xpath_value req_aw_duration   => '//Data/job/@ReqAWDuration';
has_xpath_value srm_jid           => '//Data/job/@SRMJID';
has_xpath_value session_id        => '//Data/job/@SessionID';
has_xpath_value start_count       => '//Data/job/@StartCount';
has_xpath_value start_priority    => '//Data/job/@StartPriority';
has_xpath_value start_time        => '//Data/job/@StartTime';
has_xpath_value stat_msutl        => '//Data/job/@StatMSUtl';
has_xpath_value stat_psded        => '//Data/job/@StatPSDed';
has_xpath_value stat_psutl        => '//Data/job/@StatPSUtl';
has_xpath_value state             => '//Data/job/@State';
has_xpath_value submission_time   => '//Data/job/@SubmissionTime';
has_xpath_value submit_args       => '//Data/job/@SubmitArgs';
has_xpath_value submit_host       => '//Data/job/@SubmitHost';
has_xpath_value suspend_duration  => '//Data/job/@SuspendDuration';
has_xpath_value template_set_list => '//Data/job/@TemplateSetList';
has_xpath_value user              => '//Data/job/@User';

has_xpath_value alloc_node_list   => '//Data/job/req/@AllocNodeList';
has_xpath_value alloc_partitions  => '//Data/job/req/@AllocPartition';
has_xpath_value nc_req_min        => '//Data/job/req/@NCReqMin';
has_xpath_value req_mem_per_task  => '//Data/job/req/@ReqMemPerTask';
has_xpath_value req_node_mem      => '//Data/job/req/@ReqNodeMem';
has_xpath_value req_node_proc     => '//Data/job/req/@ReqNodeProc';
has_xpath_value req_node_swap     => '//Data/job/req/@ReqNodeSwap';
has_xpath_value req_parititon     => '//Data/job/req/@ReqPartition';
has_xpath_value req_proc_per_task => '//Data/job/req/@ReqProcPerTask';
has_xpath_value tc_req_min        => '//Data/job/req/@TCReqMin';
has_xpath_value util_mem          => '//Data/job/req/@UtilMem';
has_xpath_value util_proc         => '//Data/job/req/@UtilProc';
has_xpath_value util_swap         => '//Data/job/req/@UtilSwap';

finalize_class();
